version: '3.9'

services:
  python-services: 
    build: .
  postgresDB:
    image: postgres:latest
    environment:
      POSTGRES_DB: dataTalks
      POSTGRES_PASSWORD: RedBarn23!
      POSTGRES_USER: jknox
    ports:
      - "5432:5432"
    volumes:
      - pg_data_talks:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresDB

    
volumes:
  pg_data_talks:
  pgadmin:
